apiVersion: v1
kind: Service
metadata:
  name: argocd-server-nodeport
  namespace: argocd
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
spec:
  ports:
  - name: http
    nodePort: 30081
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8080
    nodePort: 30082
  selector:
    app.kubernetes.io/name: argocd-server
  sessionAffinity: None
  type: NodePort